version: "3.9"
services:
  web:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    command: /app/deploy/web.sh
    expose:
      - $VIRTUAL_PORT
    environment:
      VIRTUAL_HOST: $VIRTUAL_HOST
      VIRTUAL_PORT: $VIRTUAL_PORT
      LETSENCRYPT_HOST: $LETSENCRYPT_HOST
      LETSENCRYPT_EMAIL: $LETSENCRYPT_EMAIL
      DEBUG: $DEBUG
      SECRET_KEY: $SECRET_KEY
      DATABASE_URL: $DATABASE_URL
      DOMAIN: $DOMAIN
      SENTRY_DSN: $SENTRY_DSN
      EMAIL_HOST: $EMAIL_HOST
      EMAIL_HOST_USER: $EMAIL_HOST_USER
      EMAIL_HOST_PASSWORD: $EMAIL_HOST_PASSWORD
      CELERY_BROKER_URL: $CELERY_BROKER_URL
      CELERY_TASK_ALWAYS_EAGER: $CELERY_TASK_ALWAYS_EAGER
      AI_SENSEI_AUTH_URL: $AI_SENSEI_AUTH_URL
      AI_SENSEI_SERVICE: $AI_SENSEI_SERVICE
      AI_SENSEI_EMAIL: $AI_SENSEI_EMAIL
      AI_SENSEI_PASSWORD: $AI_SENSEI_PASSWORD
    depends_on:
      - db
    volumes:
      - "${DATA_PATH}/static:/data/static"
      - "${DATA_PATH}/media:/data/media"
      - "${DATA_PATH}/fixtures:/data/fixtures"
  db:
    image: postgres:14.0-alpine
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "${DATA_PATH}/postgres:/var/lib/postgresql/data/pgdata"
      - "${DATA_PATH}/pg_backups:/backups"
  worker:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    command: /app/deploy/worker.sh
    environment:
      DEBUG: $DEBUG
      SECRET_KEY: $SECRET_KEY
      DATABASE_URL: $DATABASE_URL
      DOMAIN: $DOMAIN
      SENTRY_DSN: $SENTRY_DSN
      EMAIL_HOST: $EMAIL_HOST
      EMAIL_HOST_USER: $EMAIL_HOST_USER
      EMAIL_HOST_PASSWORD: $EMAIL_HOST_PASSWORD
      CELERY_BROKER_URL: $CELERY_BROKER_URL
      CELERY_TASK_ALWAYS_EAGER: $CELERY_TASK_ALWAYS_EAGER
      AI_SENSEI_AUTH_URL: $AI_SENSEI_AUTH_URL
      AI_SENSEI_SERVICE: $AI_SENSEI_SERVICE
      AI_SENSEI_EMAIL: $AI_SENSEI_EMAIL
      AI_SENSEI_PASSWORD: $AI_SENSEI_PASSWORD
    depends_on:
      - db
      - redis
    volumes:
      - "${DATA_PATH}/static:/data/static"
      - "${DATA_PATH}/media:/data/media"
      - "${DATA_PATH}/fixtures:/data/fixtures"
  redis:
    image: redis:6.2.6
