# Generated by Django 3.2.7 on 2021-11-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_auto_20211105_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='auto_join',
            field=models.BooleanField(default=True),
        ),
    ]
