# Generated by Django 3.2.7 on 2021-11-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_auto_20211105_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='win_type',
            field=models.CharField(blank=True, choices=[('points', 'Punkty'), ('resign', 'Rezygnacja'), ('time', 'Czas'), ('not_played', 'Nierozegrana')], max_length=16, null=True),
        ),
    ]
