# Generated by Django 3.2.7 on 2021-11-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0006_group_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='state',
            field=models.CharField(choices=[('draft', 'W przygotowaniu'), ('in_progress', 'Trwa'), ('finished', 'Zakończony')], max_length=16),
        ),
    ]
