# Generated by Django 3.2.9 on 2021-11-16 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0009_game_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='black',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_as_black', to='league.member'),
        ),
        migrations.AlterField(
            model_name='game',
            name='white',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_as_white', to='league.member'),
        ),
        migrations.AlterField(
            model_name='game',
            name='win_type',
            field=models.CharField(blank=True, choices=[('points', 'Punkty'), ('resign', 'Rezygnacja'), ('time', 'Czas'), ('bye', 'Bye'), ('not_played', 'Nierozegrana')], max_length=16, null=True),
        ),
    ]
