# Generated by Django 3.2.7 on 2021-11-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0010_add_bye_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ai_analyse_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='review_video_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
