# Generated by Django 3.2.9 on 2021-11-23 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0011_auto_20211121_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='black',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_as_black', to='league.member'),
        ),
        migrations.AlterField(
            model_name='game',
            name='server',
            field=models.CharField(blank=True, choices=[('OGS', 'OGS'), ('KGS', 'KGS')], max_length=3),
        ),
        migrations.AlterField(
            model_name='game',
            name='white',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_as_white', to='league.member'),
        ),
    ]
