# Generated by Django 3.2.9 on 2021-11-30 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0012_auto_20211123_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='initial_score',
            field=models.SmallIntegerField(default=0),
        ),
    ]
