# Generated by Django 3.2.9 on 2021-12-27 15:11

from django.db import migrations, models
import league.models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0013_member_initial_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='points_difference',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[league.models.points_difference_validator]),
        ),
    ]
