# Generated by Django 3.2.9 on 2021-12-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0014_alter_game_points_difference'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='egd_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='egd_pin',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
