# Generated by Django 3.2.9 on 2021-12-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0015_auto_20211227_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='availability',
            field=models.TextField(blank=True),
        ),
    ]
