# Generated by Django 3.2.9 on 2022-01-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0016_player_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_egd',
            field=models.BooleanField(default=False),
        ),
    ]
