# Generated by Django 3.2.9 on 2022-01-03 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0017_group_is_egd'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name']},
        ),
    ]
