# Generated by Django 3.2.9 on 2022-01-23 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0019_group_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['-season__number', 'name']},
        ),
    ]
