# Generated by Django 3.2.9 on 2022-01-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0020_alter_group_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_supporter',
            field=models.BooleanField(default=False),
        ),
    ]
