# Generated by Django 3.2.9 on 2022-01-30 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0021_player_is_supporter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='round',
            options={'ordering': ['number']},
        ),
    ]
