# Generated by Django 3.2.9 on 2022-02-08 16:33

import django.core.validators
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0022_alter_round_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='club',
            field=models.CharField(blank=True, max_length=4, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AddField(
            model_name='player',
            name='country',
            field=django_countries.fields.CountryField(default='PL', max_length=2),
            preserve_default=False,
        ),
    ]
