# Generated by Django 3.2.9 on 2022-02-18 14:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0024_gameaianalyseupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='egd_pin',
            field=models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
