# Generated by Django 3.2.9 on 2022-05-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0027_member_final_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='delayed_reminder_sent',
            field=models.DateTimeField(null=True),
        ),
    ]
