# Generated by Django 3.2.9 on 2022-10-04 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0028_game_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='review_updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='sgf_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
