# Generated by Django 3.2.9 on 2022-10-04 21:35
from datetime import datetime

from django.apps.registry import Apps
from django.db import migrations


BEFORE_IGLO = datetime(2020, 4, 1)


def fill_sgf_updated_and_review_updated_fields(apps: Apps, schema_editor):
    Game = apps.get_model("league", "Game")
    for game in Game.objects.all():
        default_date = game.round.end_date or game.group.season.end_date or BEFORE_IGLO
        default_datetime = datetime.fromordinal(default_date.toordinal())
        timestamp = min(default_datetime, datetime.now())
        if game.sgf and len(str(game.sgf)) > 0:
            game.sgf_updated = timestamp
        if game.review_video_link and len(str(game.review_video_link)) > 0:
            game.review_updated = timestamp
        game.save()


def clean_sgf_updated_and_review_updated_fields(apps: Apps, schema_editor):
    Game = apps.get_model("league", "Game")
    for game in Game.objects.all():
        game.sgf_updated = None
        game.review_updated = None
        game.save()


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0029_latest_sgfs_and_reviews'),
    ]

    operations = [
        migrations.RunPython(
            code=fill_sgf_updated_and_review_updated_fields,
            reverse_code=clean_sgf_updated_and_review_updated_fields
        )
    ]
