# Generated by Django 4.2 on 2023-05-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0030_latest_sgfs_and_reviews_data_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='igor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
