# Generated by Django 4.2 on 2023-05-06 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0030_latest_sgfs_and_reviews_data_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='ielo_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
