# Generated by Django 4.2 on 2023-05-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0031_player_ielo_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='ielo_rating',
        ),
        migrations.AddField(
            model_name='player',
            name='igor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
