# Generated by Django 4.2.1 on 2024-01-07 20:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0031_player_igor'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='igor_history',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), default=[], size=None),
            preserve_default=False,
        ),
    ]
