# Generated by Django 4.2.1 on 2024-01-25 20:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0032_player_igor_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='igor_history',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
    ]
