# Generated by Django 4.2.18 on 2025-03-02 23:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("league", "0034_game_upcoming_reminder_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="band_size",
            field=models.IntegerField(blank=True, help_text="Band size for banded round robin pairing", null=True),
        ),
    ]
