# Generated by Django 4.2.18 on 2025-03-03 01:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("league", "0035_add_band_size_to_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="type",
            field=models.CharField(
                choices=[("round_robin", "Każdy z każdym"), ("mcmahon", "McMahon"), ("banded", "Banded Round Robin")],
                max_length=16,
            ),
        ),
    ]
