# Generated by Django 4.2.18 on 2025-03-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("league", "0036_add_banded_group_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="point_difference",
            field=models.FloatField(
                blank=True, default=1.0, help_text="Points difference between consecutive players in ranking", null=True
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="initial_score",
            field=models.FloatField(default=0.0),
        ),
    ]
