# Generated by Django 4.2.18 on 2025-03-09 03:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("league", "0038_update_egd_approval_to_per_game"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="egd_approval",
            field=models.BooleanField(default=False),
        ),
    ]
