# Generated by Django 4.2.18 on 2025-03-11 22:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("league", "0040_add_ogs_rating_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="ogs_deviation",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="ogs_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="ogs_rating",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="ogs_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
