# Generated by Django 3.2.9 on 2021-12-04 12:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('teacher', 'Nauczyciel'), ('referee', 'Sędzia')], max_length=32), blank=True, default=list, size=None),
        ),
    ]
