name: Deploy
on:
  workflow_run:
    workflows: [ "test" ]
    branches: [ master, develop ]
    types:
      - completed
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    # Ensure only one deploy runs at a time per branch
    concurrency:
      group: deploy-${{ github.event.workflow_run.head_branch }}
      cancel-in-progress: false
    # Only deploy when:
    # 1. Tests pass successfully
    # 2. The branch is either develop or master
    # 3. The test was triggered by a push event (direct push or PR merge)
    #    not a pull_request event (PR creation/update)
    # This prevents deploys from PR test runs while ensuring deploys happen
    # after merging PRs or pushing directly to main branches
    if: >
      ${{ github.event.workflow_run.conclusion == 'success' && 
      (github.event.workflow_run.head_branch == 'develop' || github.event.workflow_run.head_branch == 'master') && 
      github.event.workflow_run.event == 'push' }}
    steps:
      - name: Set env to staging
        if: github.event.workflow_run.head_branch == 'develop'
        run: |
          echo "ENVIRONMENT=staging" >> $GITHUB_ENV
      - name: Set env to production
        if: github.event.workflow_run.head_branch == 'master'
        run: |
          echo "ENVIRONMENT=production" >> $GITHUB_ENV
      - name: Deploy
        uses: fifsky/ssh-action@master
        with:
          command: |
            export ENVIRONMENT=${{ env.ENVIRONMENT }}
            cd apps/iglo_${{ env.ENVIRONMENT }}/repo
            git fetch --all
            git checkout ${{ github.event.workflow_run.head_branch }}
            git pull --ff-only
            cd ..
            ./repo/deploy/deploy.sh
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          key: ${{ secrets.KEY}}
          args: "-tt"
