name: Deploy
on:
  workflow_run:
    workflows: [ "test" ]
    branches: [ master, develop ]
    types:
      - completed
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    # Ensure only one deploy runs at a time per branch
    concurrency:
      group: deploy-${{ github.event.workflow_run.head_branch }}
      cancel-in-progress: false
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Set env to staging
        if: github.event.workflow_run.head_branch == 'develop'
        run: |
          echo "ENVIRONMENT=staging" >> $GITHUB_ENV
      - name: Set env to production
        if: github.event.workflow_run.head_branch == 'master'
        run: |
          echo "ENVIRONMENT=production" >> $GITHUB_ENV
      - name: Deploy
        uses: fifsky/ssh-action@master
        with:
          command: |
            export ENVIRONMENT=${{ env.ENVIRONMENT }}
            cd apps/iglo_${{ env.ENVIRONMENT }}/repo
            git fetch --all
            git checkout ${{ github.event.workflow_run.head_branch }}
            git pull --ff-only
            cd ..
            ./repo/deploy/deploy.sh
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          key: ${{ secrets.KEY}}
          args: "-tt"
