name: Deploy
on:
  workflow_run:
    workflows: [ "test" ]
    branches: [ master, develop ]
    types:
      - completed
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Set branch name
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Set env to staging
        if: endsWith(github.ref, '/develop')
        run: |
          echo "ENVIRONMENT=staging" >> $GITHUB_ENV
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Set env to production
        if: endsWith(github.ref, '/master')
        run: |
          echo "ENVIRONMENT=production" >> $GITHUB_ENV
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Deploy
        uses: fifsky/ssh-action@master
        with:
          command: |
            export ENVIRONMENT=${{ env.ENVIRONMENT }}
            cd apps/iglo_${{ env.ENVIRONMENT }}/repo
            git fetch --all
            git checkout ${{ env.BRANCH_NAME }}
            git pull --ff-only
            cd ..
            ./repo/deploy/deploy.sh
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          key: ${{ secrets.KEY}}
          args: "-tt"
