name: Deploy
on: [ push ]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Set env to staging
        if: endsWith(github.ref, '/develop')
        run: |
          echo "ENVIRONMENT=staging" >> $GITHUB_ENV
      - name: Set env to production
        if: endsWith(github.ref, '/master')
        run: |
          echo "ENVIRONMENT=production" >> $GITHUB_ENV
      - name: ls -a via ssh
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd apps/iglo_${{ env.ENVIRONMENT }}/repo
            git fetch --all
            git checkout ${{ github.ref }}
            git pull --ff-only
            cd ..
            ./repo/deploy/deploy.sh
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          key: ${{ secrets.KEY}}
          args: "-tt"
