name: Test
on: [ push, pull_request ]
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup database
        run: docker run --name db -d postgres
      - name: Build docker image
        run: docker build -f deploy/Dockerfile . -t web
      - name: Run tests
        run: docker run --link db:db --env DATABASE_URL="postgres://postgres:postgres@db:5432" web python manage.py test
